services:
    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
            - ./mongodb-init:/docker-entrypoint-initdb.d
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example

    backend:
        build: ./backend
        ports:
            - "5001:5000"
        depends_on:
            - mongodb
        environment:
            - MONGO_URI=mongodb://root:example@mongodb:27017/
            - PORT=5000
        volumes:
            - ./shared:/app/shared

    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        environment:
            - WATCHPACK_POLLING=true
            - WDS_SOCKET_PORT=0
        volumes:
            - ./frontend:/app
            - /app/node_modules
            - /app/.next
            - ./shared:/app/shared
        depends_on:
            - backend
        extra_hosts:
            - "host.docker.internal:host-gateway"
volumes:
    mongodb_data:
