services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend
        environment:
            - NEXT_PUBLIC_API_URL=http://backend:8000

    backend:
        build: ./backend
        ports:
            - "8000:8000"
        depends_on:
            - mongodb
        environment:
            - MONGODB_URI=mongodb://mongodb:27017/

    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
