name: bt4103
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - jupyter
  - seaborn
  - pydantic
  - pip
  - pip:
      - langchain-core
      - langchain-ollama
      - langchain
